name: 2. Deploy Infra
on:
  push:
    branches:
      - main
    paths:
      - 'ec2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ec2/**'
  workflow_dispatch:
    inputs:
      apply:
        description: Type 'true' for apply changes!
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      environment:
        description: Select the environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
          - hfx
      
jobs:
  Terraform-Plan: # Job name
    runs-on: ubuntu-latest # The job will run on the latest version of Ubuntu
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}

    defaults:
      run:
        shell: bash
        working-directory: ./ec2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ vars.AWS_S3_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}-terraform.tfstate" -backend-config="region=${{ vars.AWS_REGION }}"
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}

      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="vars/${{ github.event.inputs.environment }}.tfvars" -out=tfplan
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}

  Terraform-Apply:
      runs-on: ubuntu-latest
      needs: Terraform-Plan
      if: github.event.inputs.apply == 'true'

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      defaults:
        run:
          shell: bash
          working-directory: ./ec2

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: latest
  
        - name: Terraform Init
          run: terraform init -backend-config="bucket=${{ vars.AWS_S3_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}-terraform.tfstate" -backend-config="region=${{ vars.AWS_REGION }}"
          env:
            TF_VAR_environment: ${{ github.event.inputs.environment }}

        - name: Terraform Validate
          run: terraform validate          
      
        - name: Terraform Plan
          run: terraform plan -var-file="vars/${{ github.event.inputs.environment }}.tfvars" -out=tfplan
          env:
            TF_VAR_environment: ${{ github.event.inputs.environment }}

        - name: Terraform Apply
          run: terraform apply tfplan