name: 2.2 Deploy Infra
on:
  workflow_dispatch:
    inputs:
      action:
        description: Choose the action (apply or destroy)
        required: true
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: Select the environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
          - hfx
      confirm_destroy:
        description: Confirm destroy action (type 'yes' to proceed)
        required: false
        default: ''
        type: string

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      TF_VAR_environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        shell: bash
        working-directory: ./ec2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ vars.AWS_S3_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}-terraform.tfstate" -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="vars/${{ github.event.inputs.environment }}.tfvars" -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply tfplan

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' && github.event.inputs.confirm_destroy == 'yes' }}
        run: terraform destroy -var-file="vars/${{ github.event.inputs.environment }}.tfvars" -auto-approve
