name: Plan & Deploy Infrastructure v2

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'vars/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'vars/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Action'
        required: true
        default: 'plan'
        options:
          - name: Plan
            value: 'plan'
          - name: Apply
            value: 'apply'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'plan'
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0    

      - name: Debug Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_S3_BUCKET=${{ env.AWS_S3_BUCKET }}"              

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" -backend-config="key=dev.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Graph
        run: terraform graph

      - name: Show Terraform Plan
        run: terraform plan -var-file="../vars/common.tfvars" -var-file="../vars/dev.tfvars" -out=tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'apply'
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.0
  
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" -backend-config="key=dev.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply tfplan
