name: 2. S3
on:
  push:
    branches:
      - main
    paths:
      - 'terraform_s3_bucket/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform_s3_bucket/**'
  workflow_dispatch:
    inputs:
      apply:
        description: Type 'true' for apply changes!
        required: false
        default: 'true'

jobs:
  terraform-plan: # Job name
    runs-on: ubuntu-latest # The job will run on the latest version of Ubuntu
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform_s3_bucket

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
      runs-on: ubuntu-latest
      needs: terraform-plan
      if: github.event.inputs.apply == 'true'

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      defaults:
        run:
          shell: bash
          working-directory: ./terraform_s3_bucket

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.0
  
        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate          
      
        - name: Terraform Plan
          run: terraform plan

        - name: Terraform Apply
          run: terraform apply tfplan