name: 2. S3_2
on:
  push:
    branches:
      - main
    paths:
      - 's3_2/**' # Запускатиметься лише при зміні в папці s3

  workflow_dispatch:

jobs:
  Plan:
    name: 'Create S3 Bucket'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: ./s3_2
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Format
      run: terraform fmt
    
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="common.tfvars"

    - name: Terraform Apply
      run: | 
        terraform apply -var-file="common.tfvars" -auto-approve
        BUCKET_NAME=$(terraform output -raw bucket_name)
        echo "AWS_S3_BUCKET=$BUCKET_NAME" >> $GITHUB_ENV