name: S3 Bucket Terraform Apply Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-s3_bucket/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-s3_bucket/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply changes'
        required: false
        default: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event.inputs.apply == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-s3_bucket

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="bucket_name=${{ secrets.BUCKET_NAME }}" -var="project=${{ secrets.PROJECT }}" -var="region=${{ secrets.AWS_REGION }}"
        working-directory: ./terraform-s3_bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
